[package]
name = "thisslime-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
attribute-derive = "0.9.1"
heck = "0.5.0"
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = "2.0.66"
tracing = "0.1.40"

[lib]
proc-macro = true
